#!/bin/bash
set -eu
URL="$1"
HASH=$(echo "$URL" | sha1sum | sed -e 's/[^0-9a-f].*//')
if test -z "$(git config "remote.$HASH.url")"; then
	git config "remote.$HASH.url" "$URL"
	git config "remote.$HASH.fetch" "+*:refs/namespaces/$HASH/*"
	git config "remote.$HASH.mirror" "true"
	git config "remote.$HASH.prune" "true"
	git config "remote.$HASH.tagOpt" "--no-tags"
fi
git fetch "$HASH"
